// Generated by CoffeeScript 1.3.3
(function() {
  var nearest;

  nearest = function(date, min) {
    var current_time, seconds;
    current_time = Math.floor(date.getTime() / 1000);
    seconds = min * 60;
    return new Date(Math.ceil(current_time / seconds) * seconds * 1000);
  };

  module.exports = nearest;

}).call(this);
